/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentaluts;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yeni
 */
public class peminjaman extends javax.swing.JFrame {

    /**
     * Creates new form peminjaman
     */
    public peminjaman(String user) {
        initComponents();
        
        nm.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        labelalamat = new javax.swing.JLabel();
        labelstruk = new javax.swing.JLabel();
        labelpolisi = new javax.swing.JLabel();
        hr = new javax.swing.JTextField();
        nm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alm = new javax.swing.JTextArea();
        nstruk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rf = new javax.swing.JButton();
        cl = new javax.swing.JButton();
        del = new javax.swing.JButton();
        pr = new javax.swing.JButton();
        pinjam = new com.toedter.calendar.JDateChooser();
        kembali = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        npolisi = new javax.swing.JTextField();
        to = new javax.swing.JButton();
        hrg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sv = new javax.swing.JButton();
        dcTglPinjam = new com.toedter.calendar.JDateChooser();
        dcTglKembali = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RENTAL MOTOR GELIPSI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(688, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        labelnama.setText("Nama Peminjam");
        getContentPane().add(labelnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        labelalamat.setText("Alamat Peminjam");
        getContentPane().add(labelalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        labelstruk.setText("Nomor Struk");
        getContentPane().add(labelstruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        labelpolisi.setText("Nomor Polisi");
        getContentPane().add(labelpolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        hr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrActionPerformed(evt);
            }
        });
        getContentPane().add(hr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 70, -1));

        nm.setEnabled(false);
        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, 30));

        alm.setColumns(20);
        alm.setRows(5);
        jScrollPane1.setViewportView(alm);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 170, 70));
        getContentPane().add(nstruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 30));

        jLabel1.setText("Tanggal Pinjam");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel2.setText("Tanggal Kembali");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        rf.setText("Refresh");
        rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfActionPerformed(evt);
            }
        });
        getContentPane().add(rf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 90, -1));

        cl.setText("Clear");
        cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clActionPerformed(evt);
            }
        });
        getContentPane().add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 90, -1));

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 90, -1));

        pr.setText("Print");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        getContentPane().add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 90, -1));
        getContentPane().add(pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 170, -1));
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 170, -1));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Peminjam", "Alamat Peminjam", "No Struk", "No Polisi", "Tgl Pinjam", "Tgl Kembali", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblData);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 920, 240));

        jLabel3.setText("Jumlah Hari");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));
        getContentPane().add(npolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 170, -1));

        to.setText("Total");
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 80, -1));

        hrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgActionPerformed(evt);
            }
        });
        getContentPane().add(hrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 170, -1));

        jLabel5.setText("Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        sv.setText("Save");
        sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svActionPerformed(evt);
            }
        });
        getContentPane().add(sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 90, -1));
        getContentPane().add(dcTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));
        getContentPane().add(dcTglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, -1));

        jLabel6.setText("Tanggal Pinjam");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        jLabel7.setText("Tanggal Kembali");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, -1, -1));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_rfActionPerformed

    private void clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clActionPerformed
        // TODO add your handling code here:
        nm.setText("");
        alm.setText("");
        nstruk.setText("");
        npolisi.setText("");
        pinjam.setDate(null);
        kembali.setDate(null);
        hr.setText("");
        hrg.setText("");
    }//GEN-LAST:event_clActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if(baris!=-1){
            String Nostruk = tblData.getValueAt(baris,2).toString();
            String SQL = "DELETE FROM `tb_rental` WHERE nostruk='"+Nostruk+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Suskes",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Suskes",JOptionPane.WARNING_MESSAGE);

            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);

        }
        
    }//GEN-LAST:event_delActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Ya gini hasilnya :3 ");
        MessageFormat footer = new MessageFormat("Page {0,number,inteer}");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);           
        }catch (java.awt.print.PrinterException e){
            System.err.format("Cannot Print %s%n", e.getMessage());
        }
        
    }//GEN-LAST:event_prActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
        int hari = Integer.parseInt(hr.getText().toString());
        int hasil = hari*20000;
        hrg.setText(""+hasil);
    }//GEN-LAST:event_toActionPerformed

    private void hrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrActionPerformed

    private void svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjamm = dateFormat.format(pinjam.getDate());
        String kembalii = dateFormat.format(kembali.getDate());
        if( "".equals(nm.getText())||
            "".equals(alm.getText())||
            "".equals(nstruk.getText())||
            "".equals(npolisi.getText())||
            "".equals(hr.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
        }else
        {
            String SQL = "INSERT INTO tb_rental(nama, alamat, nostruk, nopol, pinjam, kembali, harga)"
                    + "VALUES('"+nm.getText()
                    +"','"+alm.getText()
                    +"','"+nstruk.getText()
                    +"','"+npolisi.getText()
                    +"','"+pinjamm
                    +"','"+kembalii
                    +"','"+hr.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1)
            {
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);

            }
        }
    }//GEN-LAST:event_svActionPerformed

    private void hrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_hrgActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String kolom[] = {"nostruk","nama","alamat","nopol","pinjam","kembali", "harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tglpinjam = dateFormat.format(dcTglPinjam.getDate());
        String tglkembali = dateFormat.format(dcTglKembali.getDate());
 
        String SQL = "SELECT * FROM tb_rental WHERE pinjam='"+tglpinjam+"' AND kembali='"+tglkembali+"'";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String no_struk = rs.getString(1);
                String nama = rs.getString(2);
                String alamat = rs.getString(3);
                String no_pol = rs.getString(4);
                String tgl_pinjam = rs.getString(5);
                String tgl_kembali = rs.getString(6);
                String harga = rs.getString(7);
                String data[] = {no_struk, nama, alamat, no_pol, tgl_pinjam, tgl_kembali, harga};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String user = null;
                new peminjaman(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alm;
    private javax.swing.JButton cl;
    private com.toedter.calendar.JDateChooser dcTglKembali;
    private com.toedter.calendar.JDateChooser dcTglPinjam;
    private javax.swing.JButton del;
    private javax.swing.JTextField hr;
    private javax.swing.JTextField hrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser kembali;
    private javax.swing.JLabel labelalamat;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelpolisi;
    private javax.swing.JLabel labelstruk;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField npolisi;
    private javax.swing.JTextField nstruk;
    private com.toedter.calendar.JDateChooser pinjam;
    private javax.swing.JButton pr;
    private javax.swing.JButton rf;
    private javax.swing.JButton search;
    private javax.swing.JButton sv;
    private javax.swing.JTable tblData;
    private javax.swing.JButton to;
    // End of variables declaration//GEN-END:variables


public void selectData() {
        String kolom[] = {"nama", "alamat","nostruk", "nopol", "pinjam", "kembali", "harga"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM `tb_rental`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String nama = rs.getString(1);
                String alamat = rs.getString(2);
                String nostruk = rs.getString(3);
                String nopol = rs.getString(4);
                String pinjam = rs.getString(5);
                String kembali = rs.getString(6);
                String harga = rs.getString(7);
                String data[] = {nama, alamat, nostruk, nopol, pinjam, kembali, harga};
                dtm.addRow(data);
            }
        }catch(SQLException ex){
            Logger.getLogger(peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}